# Generated by Django 5.2.17 on 2026-09-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_case_insensitive_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive schools stay in reports and past orders but cannot be assigned new ones.'),
        ),
    ]
