# Generated by Django 5.2.17 on 2026-09-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_school_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoringcenter',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive tailoring centers stay in reports but cannot be assigned new production orders.'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive warehouses stay in reports and past orders but cannot receive new stock.'),
        ),
    ]
